development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: social_development
  pool: 5
  username: postgres
  password: 12345678

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: social_test
  pool: 5
  username: postgres
  password: 12345678
